using ThermoCal.Core.DTOs;

namespace ThermoCal.Core.Services;

public interface IEntropyChangeOfPerfectGasesApproximateService
{
    EntropyChangeOfPerfectGasesApproximateResponseDto CalculateEntropyChangeOfPerfectGasesApproximate(EntropyChangeOfPerfectGasesApproximateRequestDto request);
}