using ThermoCal.Core.DTOs;

namespace ThermoCal.Core.Services;

public interface IEntropyCalculationForUniformFlowBalancedOpenSystemService
{
    EntropyCalculationForUniformFlowBalancedOpenSystemResponseDto CalculateEntropyCalculationForUniformFlowBalancedOpenSystem(EntropyCalculationForUniformFlowBalancedOpenSystemRequestDto request);
}