using ThermoCal.Core.DTOs;

namespace ThermoCal.Core.Services;

public interface IEntropyCalculationForSteadyFlowOpenSystemService
{
    Task<CustomResponseDto<EntropyCalculationForSteadyFlowOpenSystemResponseDto>> CalculateEntropyCalculationForSteadyFlowOpenSystemAsync(EntropyCalculationForSteadyFlowOpenSystemRequestDto request);
}