using ThermoCal.Core.DTOs;

namespace ThermoCal.Core.Services;

public interface IEntropyCalculationForSteadyFlowOpenSystemService
{
    EntropyCalculationForSteadyFlowOpenSystemResponseDto CalculateEntropyCalculationForSteadyFlowOpenSystem(EntropyCalculationForSteadyFlowOpenSystemRequestDto request);
}