using ThermoCal.Core.DTOs;

namespace ThermoCal.Core.Services;

public interface IEntropyCalculationForUniformFlowBalancedOpenSystemService
{
    Task<CustomResponseDto<EntropyCalculationForUniformFlowBalancedOpenSystemResponseDto>> CalculateEntropyCalculationForUniformFlowBalancedOpenSystemAsync(EntropyCalculationForUniformFlowBalancedOpenSystemRequestDto request);
}