using ThermoCal.Core.DTOs;

namespace ThermoCal.Core.Services;

public interface IIsentropicPhaseChangeOfPerfectGasesExactService
{
    IsentropicPhaseChangeOfPerfectGasesExactResponseDto CalculateIsentropicPhaseChangeOfPerfectGasesExact(IsentropicPhaseChangeOfPerfectGasesExactRequestDto request);
}