using ThermoCal.Core.DTOs;

namespace ThermoCal.Core.Services;

public interface IIsentropicPhaseChangeOfPerfectGasesApproximateService
{
    IsentropicPhaseChangeOfPerfectGasesApproximateResponseDto CalculateIsentropicPhaseChangeOfPerfectGasesApproximate(IsentropicPhaseChangeOfPerfectGasesApproximateRequestDto request);
}