using ThermoCal.Core.DTOs;

namespace ThermoCal.Core.Services;

public interface IIsentropicPhaseChangeOfPerfectGasesExactService
{
    Task<CustomResponseDto<IsentropicPhaseChangeOfPerfectGasesExactResponseDto>> CalculateIsentropicPhaseChangeOfPerfectGasesExactAsync(IsentropicPhaseChangeOfPerfectGasesExactRequestDto request);
}