using ThermoCal.Core.DTOs;

namespace ThermoCal.Core.Services;

public interface IIsentropicPhaseChangeOfPerfectGasesApproximateService
{
    Task<CustomResponseDto<IsentropicPhaseChangeOfPerfectGasesApproximateResponseDto>> CalculateIsentropicPhaseChangeOfPerfectGasesApproximateAsync(IsentropicPhaseChangeOfPerfectGasesApproximateRequestDto request);
}